### ISSUE TITLE
Checkboxes focus states are inconsistent in "medium" size

### ISSUE THREAD

**Issue by ekynoxe** [ogcio/ogcio-ds#154]
Whilst using checkboxes in our forms in https://github.com/ogcio/formsSG-4IE, we noticed that when using 

`.govie-checkboxes-medium__input`  with `.govie-checkboxes-medium__label`, the outlines aren't shown on focus.

I believe the issue is because the css in https://github.com/ogcio/ogcio-ds/blob/main/src/govie/components/checkboxes/_index.scss#L319 references `govie-checkboxes__label` rather than `govie-checkboxes-medium__label`

Comparing this to code around this line, and to [the styles of medium Radio elements in focus](https://github.com/ogcio/ogcio-ds/blob/main/src/govie/components/radios/_index.scss#L327) (which focus styles do work as expected), I believe that the correct selector should be `.govie-checkboxes-medium__input:focus+.govie-checkboxes-medium__label:before {`

We've added a temporary fix in our application's css overrides, but ideally the fix should be in here.

**Comment by hamza14khan** [comment]
PR raised: https://github.com/ogcio/ogcio-ds/pull/155

Thanks @ekynoxe for the suggested fix.
